/**
 * Map of Babel node types to their child keys that contain traversable AST nodes.
 * @type {Record<string, string[]>}
 */
const nodeChildren = {
  'ArrayExpression': ['elements'],
  'ArrayPattern': ['elements'],
  'ArrowFunctionExpression': ['params', 'body'],
  'AssignmentExpression': ['left', 'right'],
  'AssignmentPattern': ['left', 'right'],
  'AwaitExpression': ['argument'],
  'BinaryExpression': ['left', 'right'],
  'BlockStatement': ['directives', 'body'],
  'BreakStatement': ['label'],
  'CallExpression': ['callee', 'arguments'],
  'CatchClause': ['param', 'body'],
  'ClassBody': ['body'],
  'ClassDeclaration': ['id', 'superClass', 'body'],
  'ClassExpression': ['id', 'superClass', 'body'],
  'ClassMethod': ['key', 'params', 'body'],
  'ClassPrivateMethod': ['key', 'params', 'body'],
  'ClassPrivateProperty': ['key', 'value'],
  'ClassProperty': ['key', 'value'],
  'ConditionalExpression': ['test', 'consequent', 'alternate'],
  'ContinueStatement': ['label'],
  'DebuggerStatement': [],
  'Directive': ['value'],
  'DirectiveLiteral': [],
  'DoWhileStatement': ['body', 'test'],
  'EmptyStatement': [],
  'ExportAllDeclaration': ['source'],
  'ExportDefaultDeclaration': ['declaration'],
  'ExportNamedDeclaration': ['declaration', 'specifiers', 'source'],
  'ExportNamespaceSpecifier': ['exported'],
  'ExportSpecifier': ['local', 'exported'],
  'ExpressionStatement': ['expression'],
  'File': ['program'],
  'ForInStatement': ['left', 'right', 'body'],
  'ForOfStatement': ['left', 'right', 'body'],
  'ForStatement': ['init', 'test', 'update', 'body'],
  'FunctionDeclaration': ['id', 'params', 'body'],
  'FunctionExpression': ['id', 'params', 'body'],
  'IfStatement': ['test', 'consequent', 'alternate'],
  'Import': [],
  'ImportDeclaration': ['specifiers', 'source'],
  'ImportDefaultSpecifier': ['local'],
  'ImportExpression': ['source'],
  'ImportNamespaceSpecifier': ['local'],
  'ImportSpecifier': ['imported', 'local'],
  'JSXAttribute': ['name', 'value'],
  'JSXElement': ['openingElement', 'children', 'closingElement'],
  'JSXExpressionContainer': ['expression'],
  'JSXFragment': ['openingFragment', 'children', 'closingFragment'],
  'JSXIdentifier': [],
  'JSXMemberExpression': ['object', 'property'],
  'JSXNamespacedName': ['namespace', 'name'],
  'JSXText': [],
  'LabeledStatement': ['label', 'body'],
  'LogicalExpression': ['left', 'right'],
  'MemberExpression': ['object', 'property'],
  'MetaProperty': ['meta', 'property'],
  'NewExpression': ['callee', 'arguments'],
  'ObjectExpression': ['properties'],
  'ObjectMethod': ['key', 'params', 'body'],
  'ObjectPattern': ['properties'],
  'ObjectProperty': ['key', 'value'],
  'OptionalCallExpression': ['callee', 'arguments'],
  'OptionalMemberExpression': ['object', 'property'],
  'ParenthesizedExpression': ['expression'],
  'PrivateName': ['id'],
  'Program': ['directives', 'body'],
  'RegExpLiteral': [],
  'RestElement': ['argument'],
  'ReturnStatement': ['argument'],
  'SequenceExpression': ['expressions'],
  'SpreadElement': ['argument'],
  'Super': [],
  'SwitchCase': ['test', 'consequent'],
  'SwitchStatement': ['discriminant', 'cases'],
  'TaggedTemplateExpression': ['tag', 'quasi'],
  'TemplateElement': [],
  'TemplateLiteral': ['quasis', 'expressions'],
  'ThisExpression': [],
  'ThrowStatement': ['argument'],
  'TryStatement': ['block', 'handler', 'finalizer'],
  'UnaryExpression': ['argument'],
  'UpdateExpression': ['argument'],
  'VariableDeclaration': ['declarations'],
  'VariableDeclarator': ['id', 'init'],
  'WhileStatement': ['test', 'body'],
  'YieldExpression': ['argument'],
  'TSAsExpression': ['expression', 'typeAnnotation'],
  'TSDeclareFunction': ['id', 'params', 'body'],
  'TSEnumDeclaration': ['id', 'members'],
  'TSEnumMember': ['id', 'initializer'],
  'TSInterfaceDeclaration': ['id', 'body'],
  'TSInterfaceBody': ['body'],
  'TSModuleDeclaration': ['id', 'body'],
  'TSModuleBlock': ['body'],
  'TSNonNullExpression': ['expression'],
  'TSParameterProperty': ['parameter'],
  'TSInstantiationExpression': ['expression'],
  'TSTypeAliasDeclaration': ['id', 'typeAnnotation'],
  'TSTypeAssertion': ['expression'],
  'TSTypeCastExpression': ['expression'],
  'TSTypeAnnotation': ['typeAnnotation'],
  'TSTypeParameterDeclaration': ['params'],
  'TSTypeParameterInstantiation': ['params'],
};
export {nodeChildren};
